services:
  - type: web
    name: ms-advocacia-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MASTER_SENHA_INICIAL
        value: master123
      - key: CORS_ORIGIN
        value: "*"
      - key: DATAJUD_PUBLIC_KEY
        value: "cDZHYzlZa0JadVREZDJCendQbXY6SkJlTzNjLV9TRENyQk1RdnFKZGRQdw=="
      - key: GEMINI_API_KEY
        sync: false
